<!-- Flot -->
<script src="../js/bootstrap/jquery.flot.js"></script>
<script src="../js/bootstrap/jquery.flot.tooltip.min.js"></script>
<script src="../js/bootstrap/jquery.flot.spline.js"></script>
<script src="../js/bootstrap/jquery.flot.resize.js"></script>
<script src="../js/bootstrap/jquery.flot.pie.js"></script>

<!-- Peity -->
<script src="../js/bootstrap/jquery.peity.min.js"></script>
<script src="../js/bootstrap/peity-demo.js"></script>

<!-- jQuery UI -->
<script src="../js/bootstrap/jquery-ui.min.js"></script>

<!-- GITTER -->
<script src="../js/bootstrap/jquery.gritter.min.js"></script>

<!-- Sparkline -->
<script src="../js/bootstrap/jquery.sparkline.min.js"></script>

<!-- Sparkline demo data  -->
<script src="../js/bootstrap/sparkline-demo.js"></script>

<!-- ChartJS-->
<script src="../js/bootstrap/Chart.min.js"></script>

<!-- Toastr -->
<script src="../js/bootstrap/toastr.min.js"></script>