<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Dashboard</title>

    <link href="../style/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="../style/bootstrap/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="../style/bootstrap/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="../style/bootstrap/jquery.gritter.css" rel="stylesheet">

    <link href="../style/bootstrap/animate.css" rel="stylesheet">
    <link href="../style/bootstrap/style.css" rel="stylesheet">

</head>
